// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package main

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Message_MessageType int32

const (
	Message_PING                     Message_MessageType = 0
	Message_CHAT                     Message_MessageType = 1
	Message_FOLLOW                   Message_MessageType = 2
	Message_UNFOLLOW                 Message_MessageType = 3
	Message_ORDER                    Message_MessageType = 4
	Message_ORDER_REJECT             Message_MessageType = 5
	Message_ORDER_CANCEL             Message_MessageType = 6
	Message_ORDER_CONFIRMATION       Message_MessageType = 7
	Message_ORDER_FULFILLMENT        Message_MessageType = 8
	Message_ORDER_COMPLETION         Message_MessageType = 9
	Message_DISPUTE_OPEN             Message_MessageType = 10
	Message_DISPUTE_UPDATE           Message_MessageType = 11
	Message_DISPUTE_CLOSE            Message_MessageType = 12
	Message_REFUND                   Message_MessageType = 13
	Message_OFFLINE_ACK              Message_MessageType = 14
	Message_OFFLINE_RELAY            Message_MessageType = 15
	Message_MODERATOR_ADD            Message_MessageType = 16
	Message_MODERATOR_REMOVE         Message_MessageType = 17
	Message_STORE                    Message_MessageType = 18
	Message_BLOCK                    Message_MessageType = 19
	Message_VENDOR_FINALIZED_PAYMENT Message_MessageType = 20
	Message_ERROR                    Message_MessageType = 500
)

var Message_MessageType_name = map[int32]string{
	0:   "PING",
	1:   "CHAT",
	2:   "FOLLOW",
	3:   "UNFOLLOW",
	4:   "ORDER",
	5:   "ORDER_REJECT",
	6:   "ORDER_CANCEL",
	7:   "ORDER_CONFIRMATION",
	8:   "ORDER_FULFILLMENT",
	9:   "ORDER_COMPLETION",
	10:  "DISPUTE_OPEN",
	11:  "DISPUTE_UPDATE",
	12:  "DISPUTE_CLOSE",
	13:  "REFUND",
	14:  "OFFLINE_ACK",
	15:  "OFFLINE_RELAY",
	16:  "MODERATOR_ADD",
	17:  "MODERATOR_REMOVE",
	18:  "STORE",
	19:  "BLOCK",
	20:  "VENDOR_FINALIZED_PAYMENT",
	500: "ERROR",
}

var Message_MessageType_value = map[string]int32{
	"PING":                     0,
	"CHAT":                     1,
	"FOLLOW":                   2,
	"UNFOLLOW":                 3,
	"ORDER":                    4,
	"ORDER_REJECT":             5,
	"ORDER_CANCEL":             6,
	"ORDER_CONFIRMATION":       7,
	"ORDER_FULFILLMENT":        8,
	"ORDER_COMPLETION":         9,
	"DISPUTE_OPEN":             10,
	"DISPUTE_UPDATE":           11,
	"DISPUTE_CLOSE":            12,
	"REFUND":                   13,
	"OFFLINE_ACK":              14,
	"OFFLINE_RELAY":            15,
	"MODERATOR_ADD":            16,
	"MODERATOR_REMOVE":         17,
	"STORE":                    18,
	"BLOCK":                    19,
	"VENDOR_FINALIZED_PAYMENT": 20,
	"ERROR":                    500,
}

func (x Message_MessageType) String() string {
	return proto.EnumName(Message_MessageType_name, int32(x))
}

func (Message_MessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0, 0}
}

type Chat_Flag int32

const (
	Chat_MESSAGE Chat_Flag = 0
	Chat_TYPING  Chat_Flag = 1
	Chat_READ    Chat_Flag = 2
)

var Chat_Flag_name = map[int32]string{
	0: "MESSAGE",
	1: "TYPING",
	2: "READ",
}

var Chat_Flag_value = map[string]int32{
	"MESSAGE": 0,
	"TYPING":  1,
	"READ":    2,
}

func (x Chat_Flag) String() string {
	return proto.EnumName(Chat_Flag_name, int32(x))
}

func (Chat_Flag) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2, 0}
}

type Message struct {
	MessageType          Message_MessageType `protobuf:"varint,1,opt,name=messageType,proto3,enum=Message_MessageType" json:"messageType,omitempty"`
	Payload              *any.Any            `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	RequestId            int32               `protobuf:"varint,3,opt,name=requestId,proto3" json:"requestId,omitempty"`
	IsResponse           bool                `protobuf:"varint,4,opt,name=isResponse,proto3" json:"isResponse,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetMessageType() Message_MessageType {
	if m != nil {
		return m.MessageType
	}
	return Message_PING
}

func (m *Message) GetPayload() *any.Any {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *Message) GetRequestId() int32 {
	if m != nil {
		return m.RequestId
	}
	return 0
}

func (m *Message) GetIsResponse() bool {
	if m != nil {
		return m.IsResponse
	}
	return false
}

type Envelope struct {
	Message              *Message `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Pubkey               []byte   `protobuf:"bytes,2,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	Signature            []byte   `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Envelope) Reset()         { *m = Envelope{} }
func (m *Envelope) String() string { return proto.CompactTextString(m) }
func (*Envelope) ProtoMessage()    {}
func (*Envelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *Envelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Envelope.Unmarshal(m, b)
}
func (m *Envelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Envelope.Marshal(b, m, deterministic)
}
func (m *Envelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Envelope.Merge(m, src)
}
func (m *Envelope) XXX_Size() int {
	return xxx_messageInfo_Envelope.Size(m)
}
func (m *Envelope) XXX_DiscardUnknown() {
	xxx_messageInfo_Envelope.DiscardUnknown(m)
}

var xxx_messageInfo_Envelope proto.InternalMessageInfo

func (m *Envelope) GetMessage() *Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *Envelope) GetPubkey() []byte {
	if m != nil {
		return m.Pubkey
	}
	return nil
}

func (m *Envelope) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type Chat struct {
	MessageId            string               `protobuf:"bytes,1,opt,name=messageId,proto3" json:"messageId,omitempty"`
	Subject              string               `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Message              string               `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Flag                 Chat_Flag            `protobuf:"varint,5,opt,name=flag,proto3,enum=Chat_Flag" json:"flag,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Chat) Reset()         { *m = Chat{} }
func (m *Chat) String() string { return proto.CompactTextString(m) }
func (*Chat) ProtoMessage()    {}
func (*Chat) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2}
}

func (m *Chat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Chat.Unmarshal(m, b)
}
func (m *Chat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Chat.Marshal(b, m, deterministic)
}
func (m *Chat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Chat.Merge(m, src)
}
func (m *Chat) XXX_Size() int {
	return xxx_messageInfo_Chat.Size(m)
}
func (m *Chat) XXX_DiscardUnknown() {
	xxx_messageInfo_Chat.DiscardUnknown(m)
}

var xxx_messageInfo_Chat proto.InternalMessageInfo

func (m *Chat) GetMessageId() string {
	if m != nil {
		return m.MessageId
	}
	return ""
}

func (m *Chat) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *Chat) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Chat) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *Chat) GetFlag() Chat_Flag {
	if m != nil {
		return m.Flag
	}
	return Chat_MESSAGE
}

type SignedData struct {
	SenderPubkey         []byte   `protobuf:"bytes,1,opt,name=senderPubkey,proto3" json:"senderPubkey,omitempty"`
	SerializedData       []byte   `protobuf:"bytes,2,opt,name=serializedData,proto3" json:"serializedData,omitempty"`
	Signature            []byte   `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignedData) Reset()         { *m = SignedData{} }
func (m *SignedData) String() string { return proto.CompactTextString(m) }
func (*SignedData) ProtoMessage()    {}
func (*SignedData) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{3}
}

func (m *SignedData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignedData.Unmarshal(m, b)
}
func (m *SignedData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignedData.Marshal(b, m, deterministic)
}
func (m *SignedData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignedData.Merge(m, src)
}
func (m *SignedData) XXX_Size() int {
	return xxx_messageInfo_SignedData.Size(m)
}
func (m *SignedData) XXX_DiscardUnknown() {
	xxx_messageInfo_SignedData.DiscardUnknown(m)
}

var xxx_messageInfo_SignedData proto.InternalMessageInfo

func (m *SignedData) GetSenderPubkey() []byte {
	if m != nil {
		return m.SenderPubkey
	}
	return nil
}

func (m *SignedData) GetSerializedData() []byte {
	if m != nil {
		return m.SerializedData
	}
	return nil
}

func (m *SignedData) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type SignedData_Command struct {
	PeerID               string               `protobuf:"bytes,1,opt,name=peerID,proto3" json:"peerID,omitempty"`
	Type                 Message_MessageType  `protobuf:"varint,2,opt,name=type,proto3,enum=Message_MessageType" json:"type,omitempty"`
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SignedData_Command) Reset()         { *m = SignedData_Command{} }
func (m *SignedData_Command) String() string { return proto.CompactTextString(m) }
func (*SignedData_Command) ProtoMessage()    {}
func (*SignedData_Command) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{3, 0}
}

func (m *SignedData_Command) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignedData_Command.Unmarshal(m, b)
}
func (m *SignedData_Command) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignedData_Command.Marshal(b, m, deterministic)
}
func (m *SignedData_Command) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignedData_Command.Merge(m, src)
}
func (m *SignedData_Command) XXX_Size() int {
	return xxx_messageInfo_SignedData_Command.Size(m)
}
func (m *SignedData_Command) XXX_DiscardUnknown() {
	xxx_messageInfo_SignedData_Command.DiscardUnknown(m)
}

var xxx_messageInfo_SignedData_Command proto.InternalMessageInfo

func (m *SignedData_Command) GetPeerID() string {
	if m != nil {
		return m.PeerID
	}
	return ""
}

func (m *SignedData_Command) GetType() Message_MessageType {
	if m != nil {
		return m.Type
	}
	return Message_PING
}

func (m *SignedData_Command) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

type CidList struct {
	Cids                 []string `protobuf:"bytes,1,rep,name=cids,proto3" json:"cids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CidList) Reset()         { *m = CidList{} }
func (m *CidList) String() string { return proto.CompactTextString(m) }
func (*CidList) ProtoMessage()    {}
func (*CidList) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{4}
}

func (m *CidList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CidList.Unmarshal(m, b)
}
func (m *CidList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CidList.Marshal(b, m, deterministic)
}
func (m *CidList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CidList.Merge(m, src)
}
func (m *CidList) XXX_Size() int {
	return xxx_messageInfo_CidList.Size(m)
}
func (m *CidList) XXX_DiscardUnknown() {
	xxx_messageInfo_CidList.DiscardUnknown(m)
}

var xxx_messageInfo_CidList proto.InternalMessageInfo

func (m *CidList) GetCids() []string {
	if m != nil {
		return m.Cids
	}
	return nil
}

type Block struct {
	RawData              []byte   `protobuf:"bytes,1,opt,name=rawData,proto3" json:"rawData,omitempty"`
	Cid                  string   `protobuf:"bytes,2,opt,name=cid,proto3" json:"cid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Block) Reset()         { *m = Block{} }
func (m *Block) String() string { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()    {}
func (*Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{5}
}

func (m *Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block.Unmarshal(m, b)
}
func (m *Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block.Marshal(b, m, deterministic)
}
func (m *Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block.Merge(m, src)
}
func (m *Block) XXX_Size() int {
	return xxx_messageInfo_Block.Size(m)
}
func (m *Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Block proto.InternalMessageInfo

func (m *Block) GetRawData() []byte {
	if m != nil {
		return m.RawData
	}
	return nil
}

func (m *Block) GetCid() string {
	if m != nil {
		return m.Cid
	}
	return ""
}

type Error struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	ErrorMessage         string   `protobuf:"bytes,2,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	OrderID              string   `protobuf:"bytes,3,opt,name=orderID,proto3" json:"orderID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{6}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *Error) GetOrderID() string {
	if m != nil {
		return m.OrderID
	}
	return ""
}

func init() {
	proto.RegisterEnum("Message_MessageType", Message_MessageType_name, Message_MessageType_value)
	proto.RegisterEnum("Chat_Flag", Chat_Flag_name, Chat_Flag_value)
	proto.RegisterType((*Message)(nil), "Message")
	proto.RegisterType((*Envelope)(nil), "Envelope")
	proto.RegisterType((*Chat)(nil), "Chat")
	proto.RegisterType((*SignedData)(nil), "SignedData")
	proto.RegisterType((*SignedData_Command)(nil), "SignedData.Command")
	proto.RegisterType((*CidList)(nil), "CidList")
	proto.RegisterType((*Block)(nil), "Block")
	proto.RegisterType((*Error)(nil), "Error")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 789 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0x41, 0x8f, 0x9b, 0x46,
	0x14, 0x0e, 0x0b, 0x36, 0xf6, 0xc3, 0xbb, 0x99, 0x9d, 0x6e, 0x23, 0xba, 0x4a, 0x53, 0x8b, 0x43,
	0xe5, 0x5e, 0x88, 0xb4, 0x91, 0xaa, 0x5e, 0x59, 0x18, 0x52, 0x1a, 0x0c, 0xd6, 0x18, 0xa7, 0xda,
	0x5c, 0x2c, 0x6c, 0x26, 0x2e, 0x8d, 0x0d, 0x2e, 0xe0, 0x56, 0xee, 0xad, 0x87, 0xfe, 0xa2, 0xfe,
	0x9e, 0xfe, 0x8b, 0x9e, 0xab, 0x6a, 0x86, 0xa1, 0xde, 0x4d, 0xa5, 0x95, 0x7a, 0xe2, 0xbd, 0xef,
	0x7d, 0xbc, 0x79, 0xef, 0x9b, 0x0f, 0xe0, 0x7c, 0xc7, 0xea, 0x3a, 0xdd, 0x30, 0x7b, 0x5f, 0x95,
	0x4d, 0x79, 0xfd, 0xd9, 0xa6, 0x2c, 0x37, 0x5b, 0xf6, 0x52, 0x64, 0xab, 0xc3, 0xfb, 0x97, 0x69,
	0x71, 0x94, 0xa5, 0x2f, 0x3e, 0x2e, 0x35, 0xf9, 0x8e, 0xd5, 0x4d, 0xba, 0xdb, 0xb7, 0x04, 0xeb,
	0x0f, 0x0d, 0xf4, 0x69, 0xdb, 0x0d, 0x7f, 0x0d, 0x86, 0x6c, 0x9c, 0x1c, 0xf7, 0xcc, 0x54, 0xc6,
	0xca, 0xe4, 0xe2, 0xe6, 0xca, 0x96, 0xe5, 0xee, 0xc9, 0x6b, 0xf4, 0x3e, 0x11, 0xdb, 0xa0, 0xef,
	0xd3, 0xe3, 0xb6, 0x4c, 0x33, 0xf3, 0x6c, 0xac, 0x4c, 0x8c, 0x9b, 0x2b, 0xbb, 0x3d, 0xd6, 0xee,
	0x8e, 0xb5, 0x9d, 0xe2, 0x48, 0x3b, 0x12, 0x7e, 0x0e, 0xc3, 0x8a, 0xfd, 0x74, 0x60, 0x75, 0x13,
	0x64, 0xa6, 0x3a, 0x56, 0x26, 0x3d, 0x7a, 0x02, 0xf0, 0x0b, 0x80, 0xbc, 0xa6, 0xac, 0xde, 0x97,
	0x45, 0xcd, 0x4c, 0x6d, 0xac, 0x4c, 0x06, 0xf4, 0x1e, 0x62, 0xfd, 0xa6, 0x82, 0x71, 0x6f, 0x14,
	0x3c, 0x00, 0x6d, 0x16, 0x44, 0xaf, 0xd1, 0x13, 0x1e, 0xb9, 0xdf, 0x3a, 0x09, 0x52, 0x30, 0x40,
	0xdf, 0x8f, 0xc3, 0x30, 0xfe, 0x1e, 0x9d, 0xe1, 0x11, 0x0c, 0x16, 0x91, 0xcc, 0x54, 0x3c, 0x84,
	0x5e, 0x4c, 0x3d, 0x42, 0x91, 0x86, 0x11, 0x8c, 0x44, 0xb8, 0xa4, 0xe4, 0x3b, 0xe2, 0x26, 0xa8,
	0x77, 0x42, 0x5c, 0x27, 0x72, 0x49, 0x88, 0xfa, 0xf8, 0x19, 0x60, 0x89, 0xc4, 0x91, 0x1f, 0xd0,
	0xa9, 0x93, 0x04, 0x71, 0x84, 0x74, 0xfc, 0x29, 0x5c, 0xb6, 0xb8, 0xbf, 0x08, 0xfd, 0x20, 0x0c,
	0xa7, 0x24, 0x4a, 0xd0, 0x00, 0x5f, 0x01, 0xea, 0xe8, 0xd3, 0x59, 0x48, 0x04, 0x79, 0xc8, 0xdb,
	0x7a, 0xc1, 0x7c, 0xb6, 0x48, 0xc8, 0x32, 0x9e, 0x91, 0x08, 0x01, 0xc6, 0x70, 0xd1, 0x21, 0x8b,
	0x99, 0xe7, 0x24, 0x04, 0x19, 0xf8, 0x12, 0xce, 0x3b, 0xcc, 0x0d, 0xe3, 0x39, 0x41, 0x23, 0xbe,
	0x06, 0x25, 0xfe, 0x22, 0xf2, 0xd0, 0x39, 0x7e, 0x0a, 0x46, 0xec, 0xfb, 0x61, 0x10, 0x91, 0xa5,
	0xe3, 0xbe, 0x41, 0x17, 0x9c, 0xdf, 0x01, 0x94, 0x84, 0xce, 0x1d, 0x7a, 0xca, 0xa1, 0x69, 0xec,
	0x11, 0xea, 0x24, 0x31, 0x5d, 0x3a, 0x9e, 0x87, 0x10, 0x9f, 0xe8, 0x04, 0x51, 0x32, 0x8d, 0xdf,
	0x12, 0x74, 0xc9, 0x55, 0x98, 0x27, 0x31, 0x25, 0x08, 0xf3, 0xf0, 0x36, 0x8c, 0xdd, 0x37, 0xe8,
	0x13, 0xfc, 0x1c, 0xcc, 0xb7, 0x24, 0xf2, 0x62, 0xba, 0xf4, 0x83, 0xc8, 0x09, 0x83, 0x77, 0xc4,
	0x5b, 0xce, 0x9c, 0x3b, 0xb1, 0xdb, 0x15, 0x06, 0xe8, 0x11, 0x4a, 0x63, 0x8a, 0xfe, 0x52, 0xad,
	0x0c, 0x06, 0xa4, 0xf8, 0x99, 0x6d, 0xcb, 0x3d, 0xc3, 0x16, 0xe8, 0xd2, 0x0c, 0xc2, 0x31, 0xc6,
	0xcd, 0xa0, 0x73, 0x0a, 0xed, 0x0a, 0xf8, 0x19, 0xf4, 0xf7, 0x87, 0xd5, 0x07, 0x76, 0x14, 0x06,
	0x19, 0x51, 0x99, 0x71, 0x27, 0xd4, 0xf9, 0xa6, 0x48, 0x9b, 0x43, 0xc5, 0x84, 0x13, 0x46, 0xf4,
	0x04, 0x58, 0x7f, 0x2a, 0xa0, 0xb9, 0x3f, 0xa4, 0x0d, 0xa7, 0xc9, 0x4e, 0x41, 0x26, 0x0e, 0x19,
	0xd2, 0x13, 0x80, 0x4d, 0xd0, 0xeb, 0xc3, 0xea, 0x47, 0xb6, 0x6e, 0x44, 0xf7, 0x21, 0xed, 0x52,
	0x5e, 0xe9, 0x46, 0x53, 0xdb, 0x4a, 0x37, 0xd0, 0x37, 0x30, 0xfc, 0xf7, 0x4b, 0x10, 0x1e, 0x33,
	0x6e, 0xae, 0xff, 0x63, 0xda, 0xa4, 0x63, 0xd0, 0x13, 0x19, 0xbf, 0x00, 0xed, 0xfd, 0x36, 0xdd,
	0x98, 0x3d, 0xf1, 0x75, 0x80, 0xcd, 0x07, 0xb4, 0xfd, 0x6d, 0xba, 0xa1, 0x02, 0xb7, 0xbe, 0x02,
	0x8d, 0x67, 0xd8, 0x00, 0x7d, 0x4a, 0xe6, 0x73, 0xe7, 0x35, 0x41, 0x4f, 0xf8, 0x45, 0x26, 0x77,
	0xc2, 0xa5, 0x0a, 0x77, 0x29, 0x25, 0x8e, 0x87, 0xce, 0xac, 0xbf, 0x15, 0x80, 0x79, 0xbe, 0x29,
	0x58, 0xe6, 0xa5, 0x4d, 0x8a, 0x2d, 0x18, 0xd5, 0xac, 0xc8, 0x58, 0x35, 0x6b, 0xa5, 0x52, 0x84,
	0x1e, 0x0f, 0x30, 0xfc, 0x25, 0x5c, 0xd4, 0xac, 0xca, 0xd3, 0x6d, 0xfe, 0x6b, 0xfb, 0x96, 0x14,
	0xf4, 0x23, 0xf4, 0x71, 0x61, 0xaf, 0x7f, 0x57, 0x40, 0x77, 0xcb, 0xdd, 0x2e, 0x2d, 0x32, 0x71,
	0x35, 0x8c, 0x55, 0x81, 0x27, 0x85, 0x95, 0x19, 0x9e, 0x80, 0xd6, 0xf0, 0xbf, 0xc0, 0xd9, 0x23,
	0x7f, 0x01, 0xc1, 0x78, 0xa8, 0xa5, 0xfa, 0x3f, 0xb4, 0xb4, 0x3e, 0x07, 0xdd, 0xcd, 0xb3, 0x30,
	0xaf, 0x1b, 0x8c, 0x41, 0x5b, 0xe7, 0x59, 0x6d, 0x2a, 0x63, 0x75, 0x32, 0xa4, 0x22, 0xb6, 0x5e,
	0x41, 0xef, 0x76, 0x5b, 0xae, 0x3f, 0xf0, 0x7b, 0xac, 0xd2, 0x5f, 0xc4, 0xba, 0xad, 0x28, 0x5d,
	0x8a, 0x11, 0xa8, 0xeb, 0x3c, 0x93, 0xf7, 0xce, 0x43, 0xeb, 0x0e, 0x7a, 0xa4, 0xaa, 0xca, 0x4a,
	0x74, 0x2c, 0xb3, 0xd6, 0x94, 0xe7, 0x54, 0xc4, 0x5c, 0x62, 0xc6, 0x8b, 0x72, 0x09, 0xf9, 0xde,
	0x03, 0x8c, 0x1f, 0x56, 0x56, 0x99, 0x50, 0x44, 0x9a, 0x46, 0xa6, 0xb7, 0xfd, 0x77, 0xda, 0x2e,
	0xcd, 0x8b, 0x55, 0x5f, 0x6c, 0xf5, 0xea, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf2, 0x09, 0xce,
	0x41, 0x87, 0x05, 0x00, 0x00,
}
